//Ruta para eliminar un producto por medio del id
###
DELETE http://localhost:3000/admin/delete/product/6631e01ddf7d25baf5844147
Content-Type: application/json

//eliminar usuarios pormedio del id
###
DELETE http://localhost:3000/admin/delete/users/6631cbe4e8b6a0c9246139e4
Content-Type: application/json

//Ruta para actualizar cualquier producto por medio de el id
###
PUT http://localhost:3000/admin/update/products/662eb2b5d128b2f3e2b4de2f
Content-Type: application/json

{
    "Precio":"1500"
}

//Ruta para crear un producto, espesificando la colección
###
POST http://localhost:3000/admin/create/products/toyotas
Content-Type: application/json

{
    "nombre":"prueba",
    "Precio":"1500",
    "img":"prueba"
}